### ISSUE TITLE
TV Source Unknown in Lovelace?Dashboard

### ISSUE THREAD

**Issue by meghead** [tiagofreire-pt/tv_hisense_home_assistant#6]
My Hisense TV mode 65A6GTUK requires the rcm_certchain_pem.cer and rcm_pem_privkey.pkcs8 which I've added to hisense.conf as such;

connection hisensemqtt
address <my tv address>
username hisenseservice
password multimqttservice
clientid HomeAssistant
bridge_cafile /ssl/hisense.crt
bridge_insecure true
bridge_tls_version tlsv1.2
try_private false
start_type automatic
topic +/remoteapp/# both

I've followed all the steps but Lovelace tells me  "TV Source Unkown"

Is this related perhaps to the "known_devices.yaml" I created in config but which is now depracated?

If so what should I do instead?

![Lovelace screenshot](https://user-images.githubusercontent.com/12023624/162614574-407c96d9-5bf8-4ded-b53c-d46dc12c01db.png)

**Comment by tiagofreire-pt** [comment]
Please, check the MQTT broker, with: https://github.com/tiagofreire-pt/Home_Assistant_Hisense_TV#further-debugging-or-exploring-the-mqtt-broker-inside-the-tv

**Comment by meghead** [comment]
I'm able to connect to my tv using MQTT explorer but not entirely sure what I'm looking for. Here's what I'm seeing in MQTT Explorer;

<my TVs IP>
remoteapp
mobile
broadcast
platform_service
data
ui_service
state = {"statetype":"sourceswitch","sourceid":"HDMI3","sourcename":"HDMI3","is_signal":1,"is_lock":0,"hotel_mode":0,"displayname":"HDMI3"}
data
picturesetting = {"action":"notify_value_changed","menu_id":127,"menu_value_type":"int","menu_value":1}
txtinputdata = {"vkb_status":1,"input_data":"Big Tv"}
87:f1:ef:9a:d3:4c$vidaa_common
platform_service
data
getdeviceinfo = { "eth0": "a062fb1cd66b", "wlan0": "303235e81ee8", "ip": "myip", "tv_name": "My Tv", "voice": "2", "platform": "1", "transport_protocol": "2150", "region": "4", "vidaa_support": "1", "country": "GBR", "language": "eng", "model_name": "65A53FEVS", "tv_version": "V0000.01.00S.L0923" }
c0:11:65:fb:af:f4$normal
platform_service
data
getdeviceinfo = { "eth0": "a062fb1cd66b", "wlan0": "303235e81ee8", "ip": "myip", "tv_name": "My Tv", "voice": "2", "platform": "1", "transport_protocol": "2150", "region": "4", "vidaa_support": "1", "country": "GBR", "language": "eng", "model_name": "65A53FEVS", "tv_version": "V0000.01.00S.L0923" }

**Comment by tiagofreire-pt** [comment]
You should replace the mac address of your smartphone, as stated in the tutorial:

```
executa_hisense_input_hdmi_1:
  alias: TV - Input HDMI 1
  sequence:
    - service: mqtt.publish
      data:
        topic: '/remoteapp/tv/ui_service/SMARTPHONE_MAC_ADDRESS_AUTHORIZED_PREVIOUSLY_WITH_THE_APP_REMOTENOW$normal/actions/changesource'
        payload: '{"displayname": "HDMI1","hotel_mode": "","isDemo": false,"is_lock": "","is_signal": "","sourceid": "4","sourcename": "HDMI1"}'
```

Example:

```
SMARTPHONE_MAC_ADDRESS_AUTHORIZED_PREVIOUSLY_WITH_THE_APP_REMOTENOW == AA:BB:CC:DD:EE:FF
```
